name: Deploy to Server

on:
  push:
    branches:
      - server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEYS }}

      - name: Deploy to Server
        run: |
          ssh ecs-user@47.236.31.81 'cd /opt/lampp/htdocs/github && git pull origin server'
