name: Runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
      - label-1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Testing
        run: |
          echo Runner Is Already Online
