name: Deploy to Server

on:
  push:
    branches:
      - server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          if [ ! -f ~/.ssh/id_rsa ]; then
            echo "${{ secrets.ssh_keys }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
          fi
          ssh-keyscan -H 47.236.31.81 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ecs-user@47.236.31.81 'cd /opt/lampp/htdocs/github && git pull origin main'
