name: Deploy to Server

on:
  push:
    branches:
      - server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        
      - name: Logon
        run: |
          sshpass -p "${{ secrets.SSH_PASS }}" ssh ecs-user@47.236.31.81:22
          
      - name: Check folder
        run: |
          cd /opt/lampp/htdocs/github
