name: MySQL Check

on: [push]

jobs:
  check_database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server

    - name: check
      run: |
        sudo mysql -e "SHOW DATABASES;"
        sudo mysql -e "USE nama_database; SHOW TABLES;"
        
